project:
  type: website
  output-dir: build
lang: en
language:
  section-title-appendices: "Appendix"
website:
  bread-crumbs: false       
  title: "Football Dashboard"
  search: false
  navbar:
    background: "#0a160a"        
    foreground: "#ffffff"      
    left:
      - href: project_charta.qmd
        text: Projektcharta
      - href: data_report.qmd
        text: Datenbericht
format:
  html:
    theme: cosmo
    toc: true
number-sections: true
csl: vancouver-brackets.csl
jupyter: python3
execute:
  freeze: auto
editor:
  render-on-save: true
