project:
  type: website
  output-dir: build
lang: en
language:
  section-title-appendices: "Appendix"
website:
  title: "Football Dashboard"
  search: false                  
  navbar:
    background: "#3c7726"        
    foreground: "#3c7726"        
    left:
      - href: index.qmd
        text: Dashboard
      - href: project_charta.qmd
        text: Projektcharta
      - href: data_report.qmd
        text: Datenbericht
  sidebar:
    style: "floating"
    search: false                
    contents:
      - index.qmd
format:
  html:
    theme: cosmo
    toc: true
number-sections: true
csl: vancouver-brackets.csl
jupyter: python3
execute:
  freeze: auto
editor:
  render-on-save: true
